# Generated by Django 6.1 on 2026-08-11 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='URL uchun: /wedding/<slug>/', unique=True)),
                ('groom_name', models.CharField(max_length=100, verbose_name='Kuyov ismi')),
                ('bride_name', models.CharField(max_length=100, verbose_name='Kelin ismi')),
                ('event_date', models.DateTimeField(verbose_name="To'y sanasi va vaqti")),
                ('quote_text', models.TextField(blank=True, verbose_name='Oyat/hadis matni')),
                ('quote_source', models.CharField(blank=True, max_length=150, verbose_name='Oyat manbasi')),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='weddings/covers/')),
                ('intro_greeting', models.CharField(blank=True, default='QADRLI AZIZLARIMIZ!', max_length=200)),
                ('intro_text', models.TextField(blank=True, verbose_name='Taklif matni')),
                ('intro_photo', models.ImageField(blank=True, null=True, upload_to='weddings/intro/')),
                ('location_name', models.CharField(blank=True, max_length=150, verbose_name='Restoran nomi')),
                ('location_address', models.TextField(blank=True, verbose_name="To'liq manzil")),
                ('location_lat', models.FloatField(blank=True, null=True)),
                ('location_lng', models.FloatField(blank=True, null=True)),
                ('google_maps_url', models.URLField(blank=True)),
                ('yandex_maps_url', models.URLField(blank=True)),
                ('dashboard_password', models.CharField(help_text="To'y egasi mehmonlar ro'yxatini ko'rish uchun kiritadigan parol", max_length=128, verbose_name='Admin panel paroli')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weddings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "To'y taklifnomasi",
                'verbose_name_plural': "To'y taklifnomalari",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgramItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('title', models.CharField(max_length=150)),
                ('icon', models.CharField(choices=[('drink', 'Bokal'), ('rings', 'Uzuklar'), ('food', 'Taom'), ('fireworks', 'Salyut')], default='drink', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_final', models.BooleanField(default=False, help_text='Oxirgi nuqta (masalan Yakuni)')),
                ('wedding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program', to='weddings.wedding')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LocationPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='weddings/location/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('wedding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_images', to='weddings.wedding')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Mehmon ismi')),
                ('guest_count', models.PositiveSmallIntegerField(default=1, verbose_name='Mehmonlar soni')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('coming', 'Keladi'), ('not_coming', 'Kela olmaydi')], default='pending', max_length=20)),
                ('wish', models.TextField(blank=True, verbose_name='Tilak / izoh')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('wedding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='weddings.wedding')),
            ],
            options={
                'verbose_name': 'Mehmon',
                'verbose_name_plural': 'Mehmonlar',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
